(deftemplate symptom(slot name))
(deftemplate observation(slot name))
(deftemplate tonometry_result(slot result))
(deftemplate slit_lamp_result(slot result))
(deftemplate patient(slot name)(slot age)(slot sex)(slot occupation))
(deftemplate medical_history(slot pre_existing))
(deftemplate diagnosis(slot name))